### ISSUE TITLE
URI different for inband SCTE35 event vs. MPD SCTE35 event

### ISSUE THREAD

**Issue by waqarz** [Dash-Industry-Forum/DASH-IF-IOP#199] opened 2018-08-02 16:17 UTC
URI seems different for inband SCTE35 event (urn:scte:scte35:2013:bin) vs. MPD SCTE35 event (urn:scte:scte35:2014:xml+bin) according to Section 5.4.2.2. of DASH-IF IOP guideline.

Please clarify

**Comment by ghughes1138** [comment] 2018-08-07 19:11
There are three schemes defined by SCTE for carriage of SCTE 35 message in events.

urn:scte:scte35:2013:xml  indicates that the SCTE 35 message is carried in accordance with the scte35.xsd. The base element is Signal, an xsd group which allows a choice of "SpliceInfoSection", a parsable XML representation of the SCTE 35 message, or "Binary", which is a base64 representation of the SCTE 35 message.

urn:scte:scte35:2014:xml+bin is a subset that only allows for the base64 representation (Signal.Binary).

urn:scte:scte35:2013:bin indicates that the event is direct binary copy of the SCTE 35 splice_info_section. This was intended for inband carriage.

gary

**Comment by RufaelDev** [comment] 2018-10-25 09:29
one other issue related to this is that the urn is not registered with IANA, this must be an oversight by scte
https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml , this is a point for scte but it might be worth tracking it here

**Comment by ghughes1138** [comment] 2018-10-25 22:04
That should have been taken care of a couple of years ago, and impacts more than SCTE 35. I’ll let the secretariat know.

gary

**Comment by haudiobe** [comment] 2018-11-07 07:55
Gary does changes over the next 24 hours

- There are a couple of edits needed to 5.4.2.2.1, but “word with friends” won’t let me open the doc for editing.
- there is a reference to DVS 1208 which should be changed to SCTE 214-3. The DVS numbers are assigned for internal use while documents are being edited and are not usually accessible outside of the SCTE standards workspace. 1208 became SCTE 214-3 when published.
- the figure in that section shows carriage of an XML representation of the site 35 message in ‘emsg’ while in the text we recommend using a binary representation. I have attached a word doc containing a corrected figure. It is a Visio object and since I don’t work for any particular company anymore I don’t have access to anything that will convert it.
- I’ve just finished editing parts 1,2,3 of SCTE 214 to consolidate the SCTE 35 info into part 1 so a subsequent revision of the IOP will need some cleanup. We won’t publish the revised SCTE 214 until early next year.

**Comment by haudiobe** [comment] 2018-11-07 07:55
addressed in v4.2.4

**Closed by haudiobe** 2018-11-07 07:55 UTC
